package com.example.rmtsampleflight;
/*
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 */

/**
 * A class that holds configurations for the service version. 
 */
public class ServiceVersionConfigurations 
{
	public static final String CATALOG_SERVICE_URL = "/sap/opu/odata/IWFND/CATALOGSERVICE/";
	public static final String TECHNICHAL_SERVICE_NAME = "/IWFND/SG_SAMPLE_RMT_SFLIGHT";
	public static final int TECHNICHAL_SERVICE_VERSION_MIN = 1;
	public static final int TECHNICHAL_SERVICE_VERSION_MAX = 1;
}